### ISSUE TITLE
Attack icon is displayed next to the chesspiece insted of on top of it

### ISSUE THREAD

**Issue by SEGMK** [FoRoKo1o/ChessagonClient#7]
![image](https://github.com/user-attachments/assets/0357cd56-6c1e-460e-ab88-ab2a943f1217)

**Comment by FoRoKo1o** [comment]
![image](https://github.com/user-attachments/assets/da88b655-7302-421a-a8a8-a6d662b0b6d0)
Remove sidebar to fix issue

**Comment by SEGMK** [comment]
"REmOvE SiDe BAr To FiX IsSuE"...
